on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-06-09
          override: true
          components: rustfmt, clippy
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D clippy::pedantic -D clippy::all
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --ignored
